[package]
name = "factory_extract"
version = "0.1.0"
authors = ["Berkus Decker <berkus+github@metta.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
nom = "6.0.1"
